CFLAGS=-Wall -g -std=c11
CC=gcc

ex1: ex1.c
	$(CC) -o ex1 ex1.c $(CFLAGS)

all:
	$(CC) -o ex1 ex1.c $(CFLAGS)
	$(CC) -o ex3 ex3.c $(CFLAGS)
	$(CC) -o ex7 ex7.c $(CFLAGS)
	$(CC) -o ex11 ex11.c $(CFLAGS)

clean:
	rm -f ex1 ex3 ex7 ex11
